### ISSUE TITLE
Feature Request --- Translation

### ISSUE THREAD

**Issue by CEOXeon** [SuhasDissa/Food-E-App#1]
Can you add a Weblate or Crowdin Project so that we can translate this app?

**Comment by SuhasDissa** [comment]
I really like that idea. But I have never used Weblate or Crowdin before. I'll try my best.

**Comment by SuhasDissa** [comment]
I managed to start a Weblate project to translate the app UI
Translating the [Additives database](https://github.com/SuhasDissa/E-Number-Database) won't be that easy.

**Comment by CEOXeon** [comment]
Maybe you can use XML instead of SQL
for loading the additives. So you can write a simple Python Script that converts the Json file, that is in your other repo, to XML.
Therefore it's easier to translate with Weblate.

There are many pre-made scripts on the internet.

**Comment by SuhasDissa** [comment]
You can use [Crowdin](https://crowdin.com/project/food-e-app)

**Comment by CEOXeon** [comment]
The database doesn't show/load after Version 2.0

**Comment by SuhasDissa** [comment]
Are you talking about this #8  issue ?
I already fixed that in the latest release. Uninstall the old app and install the new one.
