### ISSUE TITLE
Suggest improvements

### ISSUE THREAD

**Issue by SimoLRepo** [SuhasDissa/Food-E-App#13]
Hi, I wanted to ask if it would also be possible to add "cosmetic ingredients harmful to health" as in the <a href="https://play.google.com/store/apps/details?id=com.zorrosoft.android.ingred">Ingred</a> application.

I also wanted to point out that in English the term "Halal" has no meaning.

The phrase "Halal Status" could be replaced with "Hazard Status" by dividing the various levels into Dangerous, Tolerable, Safe.

Thank you.

**Comment by SuhasDissa** [comment]
> I wanted to ask if it would also be possible to add "cosmetic ingredients harmful to health" as in the [Ingred](https://play.google.com/store/apps/details?id=com.zorrosoft.android.ingred) application.

Yea its possible. But I'm no expert in this field. So I have to find a reliable source of information. I'll try my best.

> The phrase "Halal Status" could be replaced with "Hazard Status" by dividing the various levels into Dangerous, Tolerable, Safe.

Halal does not mean how healthy or unhealthy an item is. I guess Its something related to Islamic religion. I added that "Halal Status" because it was requested #6

**Comment by SuhasDissa** [comment]
Closing this issue now.

Take a look at #22
