### ISSUE TITLE
The ability search open food facts.

### ISSUE THREAD

**Issue by Wjxfi** [SuhasDissa/Food-E-App#16]

**Comment by SuhasDissa** [comment]
Can you give me some examples to better understand your request?

**Comment by SuhasDissa** [comment]
### FYI: You can search for any ingredient or E number

![Screenshot_20230522_182450_Food-E](https://github.com/SuhasDissa/Food-E-App/assets/64766434/57cec238-b68b-45df-8e7f-1f929cb0370d)

**Comment by Marlowe345** [comment]
That sounds out of scope for a simple app about E-number additives, I don't think a single one of those is a food additive. I'd recommend the Open Food Facts database, or the Energize app.

**Comment by SuhasDissa** [comment]
I found the Open Food Facts API documentation a bit confusing. I couldn't find a proper API endpoint to search the database, so I had to resort to a somewhat hacky workaround. 
I was able to get the results I wanted, but I'm sure there's a better way to do it. If you know of a better way, please let me know!

This is the endpoint I found -> [https://world.openfoodfacts.org/cgi/search.pl?search_terms=cream+cracker&search_simple=1&action=process&fields=code,product_name,brands,image_thumb_url&json=1](https://world.openfoodfacts.org/cgi/search.pl?search_terms=cream+cracker&search_simple=1&action=process&fields=code,product_name,brands,image_thumb_url&json=1)

I'll continue my work in the meantime.
