### ISSUE TITLE
Health Rating being "?" for every additive
When will you fix it?

### ISSUE THREAD

**Issue by Wjxfi** [SuhasDissa/Food-E-App#27]

**Comment by SuhasDissa** [comment]
I can't do that alone
I need your help with that #22

**Comment by SuhasDissa** [comment]
I bet you didn't see this one either 👉 #26

**Comment by SuhasDissa** [comment]
To edit any additive details you need to create an account [here](https://food-e-web-production.up.railway.app/register)
You only need to enter your GitHub username. No need of email or your real name. 

There are two reasons for requiring authentication to edit the database:
- To prevent unauthorized users from making changes that could damage or corrupt the data.
- To give credit to contributors for their work.

**Comment by SuhasDissa** [comment]
Main goal is to let people fix small typos and add additional info.

**Comment by SuhasDissa** [comment]
> To edit any additive details you need to create an account [here](https://food-e-web-production.up.railway.app/register)
> You only need to enter your GitHub username. No need of email or your real name. 
> 
> There are two reasons for requiring authentication to edit the database:
> - To prevent unauthorized users from making changes that could damage or corrupt the data.
> - To give credit to contributors for their work.
> 

Temporary removed authentication requirement. Now anyone can submit changes.

**Comment by SuhasDissa** [comment]
Temporarily hiding the health status until a good solution is found
