### ISSUE TITLE
Replace halal with another word

### ISSUE THREAD

**Issue by Wjxfi** [SuhasDissa/Food-E-App#29]
No one knows this word except the followers of a religion that is almost non-existent in my country.

**Comment by SuhasDissa** [comment]
What if I use a stamp like this ,

![istockphoto-1304402767-612x612.jpg](https://github.com/SuhasDissa/Food-E-App/assets/64766434/3cf78ae8-b487-4990-bcd0-5b030156b918)

Only for halal certified additives and remove halal status from other additives
