### ISSUE TITLE
Ability to click on additives in food product information

### ISSUE THREAD

**Issue by ivan-avalos** [SuhasDissa/Food-E-App#38]
In the food additives section of the scanned product, there's the “additives” section with the additive codes. If I want to find more information about them, I need to go back and click the search button, manually introduce E-code, and then get the description. That's not what I expected when I installed the app.

![Screenshot_20230625-135351](https://github.com/SuhasDissa/Food-E-App/assets/16617314/e896c680-0622-4f56-b91e-0f1a6cdffaa6)

**Comment by SuhasDissa** [comment]
Hey there, Thank you for your suggestion. I will add that option very soon.

**Comment by SuhasDissa** [comment]
I bet you can't wait to try this feature. So here's a pre-release just for you :)

[FoodE-v3.2 pre-release.zip](https://github.com/SuhasDissa/Food-E-App/files/11872831/FoodE-v3.2.pre-release.zip)

**Comment by ivan-avalos** [comment]
It's perfect! It makes a world of difference! Thank you so much.
