### ISSUE TITLE
Food additives translation 

### ISSUE THREAD

**Issue by Turhvjbufv** [SuhasDissa/Food-E-App#42]
I know it was talked about in #1 but nothing has changed since, use crowdin or maybe you can even implement in app translation tool like lingva or deepL

**Comment by SuhasDissa** [comment]
I was able to successfully add lingva translation feature to this app. There are some improvements to be done so it will take some time to publish a new release.

Thank you for your suggestions.

**Comment by SuhasDissa** [comment]
Added Cloud translations in the latest release

**Comment by Turhvjbufv** [comment]
Nice, thank you
