### ISSUE TITLE
Translation problems

### ISSUE THREAD

**Issue by Turhvjbufv** [SuhasDissa/Food-E-App#44]
Food additives titles do not translate![Screenshot.png](https://github.com/SuhasDissa/Food-E-App/assets/91851160/979758df-6837-4ce6-bd0c-c4599653e07d)
(I have translation on and not set on English)

Also right to left translated text does not appear right(sorry for not sharing screenshots, you can test it yourself)

**Comment by SuhasDissa** [comment]
Titles are not programmed to translate. Mainly for two reasons.
- Most languages don't have native words for these names
- Translating a list of words realtime is too bad for performance and cost a lot of network bandwidth.

**Comment by SuhasDissa** [comment]
Can you be more specific about that "left to right translated text" thing?

**Comment by Turhvjbufv** [comment]
> Titles are not programmed to translate. Mainly for two reasons.
> - Most languages don't have native words for these names
> - Translating a list of words realtime is too bad for performance and cost a lot of network bandwidth.

1.are you sure about that, maybe for the uncommon ones you are right but I'm pretty sure for a lot of them they do have native words
2. It's already translating a list of words what does two or three more matter(genuinely asking)?

**Comment by Turhvjbufv** [comment]
> Can you be more specific about that "left to right translated text" thing?

The text shows on the left margin instead of the right margin

**Comment by SuhasDissa** [comment]
> 2. It's already translating a list of words what does two or three more matter(genuinely asking)?

Oh I thought you were asking me to translate the additive titles in the additive list view.
Sorry for the misunderstanding.

**Comment by Turhvjbufv** [comment]
> > 2. It's already translating a list of words what does two or three more matter(genuinely asking)?
> 
> Oh I thought you were asking me to translate the additive titles in the additive list view.
> Sorry for the misunderstanding.

No no it was my fault for not being specific and the screenshot didn't help

**Comment by SuhasDissa** [comment]
I guess you meant "Right to left languages" like Arabic?

**Comment by Turhvjbufv** [comment]
I even double checked to see that I wrote right to left I'm dumb af

**Comment by Turhvjbufv** [comment]
Yeah I meant right to left

**Comment by SuhasDissa** [comment]
Anyway can you please tell me a specific language that you are having problems with? So its easier to test.

**Comment by Turhvjbufv** [comment]
Sure, don't want to publicize that so do you have matrix or something like that?

**Comment by SuhasDissa** [comment]
Check my bio for matrix link

**Comment by Turhvjbufv** [comment]
Btw can you please add an option to translate to a specific language instead of the phones Language

**Comment by SuhasDissa** [comment]
That option is already there (only in Android 13 and above)

**Comment by Turhvjbufv** [comment]
No way to add that to lower Android devices?

**Comment by Turhvjbufv** [comment]
Maybe looking into "translate you" and "lentil translate" can help you
