### ISSUE TITLE
Use Crowdin to translate additive details

### ISSUE THREAD

**Issue by Tiberth** [SuhasDissa/Food-E-App#59]

**Comment by SuhasDissa** [comment]
Hi there,

I'm so sorry for not responding sooner.
While it is technically possible to use Crowdin to translate the Additive database, I don't think it's the best solution.
There are currently 562 additives in the database, and translating them one by one for each language would be a huge undertaking. Plus, maintaining the database with all those translations would be a lot of work.

So I'm not willing to do this.
Hope you understand.
Thank You.

**Comment by SuhasDissa** [comment]
However, I don't think crowdin can translate sqlite databases. And I couldn't find any documentation or examples of using multilingual databases in Android.

Also, I'm not underestimating Crowdin. I meant that this project doesn't have enough contributors to make crowdin translate a better alternative than the current solution.

**Comment by inson1** [comment]
@SuhasDissa I think it would be great if it was on github in xml format, so peope can save it etc. and lets say database could just get new version of the data from github every day.
