### ISSUE TITLE
[Feature Request] Add halal marker

### ISSUE THREAD

**Issue by MuntashirAkon** [SuhasDissa/Food-E-App#6]
For muslims (and others who follow similar guidelines), it would be very helpful to find whether an E code is halal (i.e. permissible) or not. There's a database of such markers here: https://ecodehalalcheck.com/

**Comment by SuhasDissa** [comment]
Thank you for your suggestion. I just added that feature (check the latest release).
Please check it out and let me know if you find any issues.

**Comment by MuntashirAkon** [comment]
Thanks.

**Comment by MuntashirAkon** [comment]
Just tested the new release. The list is empty, possibly because you forgot to push the updated database.

**Comment by SuhasDissa** [comment]
> Just tested the new release. The list is empty, possibly because you forgot to push the updated database.

Yea somehow it was not pushed 🤔. I will fix that soon

**Comment by SuhasDissa** [comment]
I fixed the issue in the latest release. Please check it out. Pardon any inconvenience caused. 🙂

**Comment by MuntashirAkon** [comment]
Thanks. It's working now.

**Comment by Viohl** [comment]
Could we also have the ability to toggle this off please? It just takes up space for those that do not practice.
Kind regards

**Comment by SuhasDissa** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add Halal status](https://trello.com/c/RYjUkkNU/8-add-halal-status)
