### ISSUE TITLE
1.0 is working / 2.0 is showing nothing

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [SuhasDissa/Food-E-App#8]
# Tested phone

## Samsung S21 5G, Android 13

![IMG_20230518_232133_960](https://github.com/SuhasDissa/Food-E-App/assets/61406324/72b8493a-0928-4f5b-9f5e-d581b7c67ab4)
![IMG_20230518_232139_144](https://github.com/SuhasDissa/Food-E-App/assets/61406324/4e83a3ad-0bbf-494d-9e39-bc7ddbcd7078)

**Comment by SuhasDissa** [comment]
Sorry for that. I built that apk with GitHub actions. And I just noticed that the updated database was not pushed to the GitHub repo.

I will fix that soon.

**Comment by SuhasDissa** [comment]
I fixed the issue in the latest release. Please check it out. Pardon any inconvenience caused. 🙂

**Comment by SuhasDissa** [comment]
> Why is this issue closed? Is there an new version ?

Issue was fixed in [this](https://github.com/SuhasDissa/Food-E-App/releases/tag/v2.0) release ( same release with updated apk)

By the way I already released **Food-E v2.1** with added favorites support. Check it out!

**Comment by mondlicht-und-sterne** [comment]
"Settings" and "About" is German

But the whole E-number (i.e. the database) is still english.

**Comment by SuhasDissa** [comment]
> "Settings" and "About" is German
> 
> But the whole E-number (i.e. the database) is still english.

There's no official android way to translate databases. So I still didn't figure out a way to translate the database.

But as a workaround I added the **Copy Info** button to copy text and translate it with translator apps such as "Google Translate" . Hope it helps!

**Comment by SuhasDissa** [comment]
> "Settings" and "About" is German
> 
> But the whole E-number (i.e. the database) is still english.

Added Cloud translation for additive details in the latest release.
